let FILEMAKER_URL = 'https://www.server-lpcr.com.do';
let FILEMAKER_USER = process.env.FILEMAKER_USER;
let FILEMAKER_PASSWORD = process.env.FILEMAKER_PASSWORD;
let FILEMAKER_DATABASE = process.env.FILEMAKER_DATABASE;
let FILEMAKER_RESULTADOSLAYOUT = 'listado_estudios_data_api';
let FILEMAKER_MEDICOSLAYOUT = 'medicos_data-api';
let FILEMAKER_PUBLICACIONESLAYOUT = 'publicaciones_data-api';
let FILEMAKER_CREDENTIALS = `${FILEMAKER_USER}:${FILEMAKER_PASSWORD}`;
let FILEMAKER_CREDENTIALS_BASE64 = Buffer.from(FILEMAKER_CREDENTIALS).toString(
  'base64',
);

// Configuración para TheFactoryHKA e-CF API
let THEFACTORY_BASE_URL = 'https://demoemision.thefactoryhka.com.do/api';
let THEFACTORY_AUTH_URL = `${THEFACTORY_BASE_URL}/Autenticacion`;
let THEFACTORY_ENVIAR_URL = `${THEFACTORY_BASE_URL}/Enviar`;
let THEFACTORY_ESTATUS_URL = `${THEFACTORY_BASE_URL}/EstatusDocumento`;
let THEFACTORY_EMAIL_URL = `${THEFACTORY_BASE_URL}/EnvioCorreo`;
let THEFACTORY_ANULACION_URL = `${THEFACTORY_BASE_URL}/Anulacion`;
let THEFACTORY_USUARIO = process.env.THEFACTORY_USUARIO;
let THEFACTORY_CLAVE = process.env.THEFACTORY_CLAVE;
let THEFACTORY_RNC = process.env.THEFACTORY_RNC;

module.exports = {
  FILEMAKER_URL,
  FILEMAKER_DATABASE,
  FILEMAKER_CREDENTIALS_BASE64,
  FILEMAKER_RESULTADOSLAYOUT,
  FILEMAKER_MEDICOSLAYOUT,
  FILEMAKER_PUBLICACIONESLAYOUT,
  THEFACTORY_BASE_URL,
  THEFACTORY_AUTH_URL,
  THEFACTORY_ENVIAR_URL,
  THEFACTORY_ESTATUS_URL,
  THEFACTORY_EMAIL_URL,
  THEFACTORY_ANULACION_URL,
  THEFACTORY_USUARIO,
  THEFACTORY_CLAVE,
  THEFACTORY_RNC,
};
